import type { BotDifficulty } from "@/lib/types";

export type BotProfile = {
  id: BotDifficulty;
  name: string;
  avatar: string;
  elo: number;
  title: string;
  description: string;
  personality: "friendly" | "aggressive" | "defensive" | "tactical" | "endgame" | "universal" | "engine";
  openingStyle: "open" | "solid" | "gambit" | "classical" | "universal";
  useStockfish: boolean;
  stockfishDepth: number;
  stockfishMoveTime: number;
  stockfishSkillLevel: number;
  fallbackDepth: number;
  blunderChance: number;
  mistakeChance: number;
  tacticalBias: number;
  thinkDelayMs: [number, number];
};

export const botProfiles: BotProfile[] = [
  {
    id: "elo-200",
    name: "Milo",
    avatar: "MI",
    elo: 200,
    title: "Beginner Bot",
    description: "Plays very loose moves, misses simple tactics, and is built for brand-new players.",
    personality: "friendly",
    openingStyle: "universal",
    useStockfish: false,
    stockfishDepth: 1,
    stockfishMoveTime: 120,
    stockfishSkillLevel: 0,
    fallbackDepth: 0,
    blunderChance: 0.52,
    mistakeChance: 0.3,
    tacticalBias: 0.08,
    thinkDelayMs: [300, 700],
  },
  {
    id: "elo-400",
    name: "Nia",
    avatar: "NI",
    elo: 400,
    title: "Easy Bot",
    description: "Spots simple checks and captures but still gives away material often.",
    personality: "friendly",
    openingStyle: "classical",
    useStockfish: false,
    stockfishDepth: 1,
    stockfishMoveTime: 160,
    stockfishSkillLevel: 2,
    fallbackDepth: 0,
    blunderChance: 0.4,
    mistakeChance: 0.26,
    tacticalBias: 0.16,
    thinkDelayMs: [350, 850],
  },
  {
    id: "elo-600",
    name: "Rook",
    avatar: "RO",
    elo: 600,
    title: "Beginner Tactics Bot",
    description: "Looks for direct threats and captures but still collapses under pressure.",
    personality: "tactical",
    openingStyle: "open",
    useStockfish: false,
    stockfishDepth: 2,
    stockfishMoveTime: 220,
    stockfishSkillLevel: 4,
    fallbackDepth: 1,
    blunderChance: 0.24,
    mistakeChance: 0.24,
    tacticalBias: 0.3,
    thinkDelayMs: [400, 900],
  },
  {
    id: "elo-800",
    name: "Alex",
    avatar: "AX",
    elo: 800,
    title: "Club Beginner",
    description: "A friendly club bot that develops pieces and notices many one-move threats.",
    personality: "universal",
    openingStyle: "classical",
    useStockfish: true,
    stockfishDepth: 2,
    stockfishMoveTime: 260,
    stockfishSkillLevel: 5,
    fallbackDepth: 2,
    blunderChance: 0.12,
    mistakeChance: 0.22,
    tacticalBias: 0.45,
    thinkDelayMs: [450, 1000],
  },
  {
    id: "elo-1000",
    name: "Iris",
    avatar: "IR",
    elo: 1000,
    title: "Easy Tactical Bot",
    description: "Plays more coherent chess, punishes hanging pieces, and still makes human mistakes.",
    personality: "tactical",
    openingStyle: "open",
    useStockfish: true,
    stockfishDepth: 3,
    stockfishMoveTime: 320,
    stockfishSkillLevel: 7,
    fallbackDepth: 2,
    blunderChance: 0.08,
    mistakeChance: 0.16,
    tacticalBias: 0.56,
    thinkDelayMs: [500, 1100],
  },
  {
    id: "elo-1200",
    name: "Theo",
    avatar: "TH",
    elo: 1200,
    title: "Weekend Player",
    description: "Balanced play, fewer blunders, and better protection of loose pieces.",
    personality: "universal",
    openingStyle: "solid",
    useStockfish: true,
    stockfishDepth: 4,
    stockfishMoveTime: 420,
    stockfishSkillLevel: 9,
    fallbackDepth: 3,
    blunderChance: 0.05,
    mistakeChance: 0.12,
    tacticalBias: 0.6,
    thinkDelayMs: [600, 1250],
  },
  {
    id: "elo-1400",
    name: "Mara",
    avatar: "MA",
    elo: 1400,
    title: "Sharp Club Bot",
    description: "A more stable sparring bot with stronger development and cleaner tactics.",
    personality: "aggressive",
    openingStyle: "gambit",
    useStockfish: true,
    stockfishDepth: 5,
    stockfishMoveTime: 560,
    stockfishSkillLevel: 11,
    fallbackDepth: 3,
    blunderChance: 0.03,
    mistakeChance: 0.08,
    tacticalBias: 0.68,
    thinkDelayMs: [650, 1450],
  },
  {
    id: "elo-1600",
    name: "Dorian",
    avatar: "DO",
    elo: 1600,
    title: "Hard Bot",
    description: "Calculates concrete lines better and converts loose tactics more reliably.",
    personality: "tactical",
    openingStyle: "open",
    useStockfish: true,
    stockfishDepth: 6,
    stockfishMoveTime: 750,
    stockfishSkillLevel: 13,
    fallbackDepth: 4,
    blunderChance: 0.018,
    mistakeChance: 0.05,
    tacticalBias: 0.76,
    thinkDelayMs: [700, 1600],
  },
  {
    id: "elo-1800",
    name: "Selene",
    avatar: "SE",
    elo: 1800,
    title: "Defensive Expert",
    description: "Defends well, misses very little, and forces you to earn your attack.",
    personality: "defensive",
    openingStyle: "solid",
    useStockfish: true,
    stockfishDepth: 7,
    stockfishMoveTime: 900,
    stockfishSkillLevel: 15,
    fallbackDepth: 5,
    blunderChance: 0.01,
    mistakeChance: 0.03,
    tacticalBias: 0.7,
    thinkDelayMs: [850, 1800],
  },
  {
    id: "elo-2000",
    name: "Victor",
    avatar: "VI",
    elo: 2000,
    title: "Master Trainer",
    description: "Serious practical bot with stronger calculation, openings, and endgame conversion.",
    personality: "universal",
    openingStyle: "classical",
    useStockfish: true,
    stockfishDepth: 8,
    stockfishMoveTime: 1150,
    stockfishSkillLevel: 17,
    fallbackDepth: 5,
    blunderChance: 0.004,
    mistakeChance: 0.015,
    tacticalBias: 0.82,
    thinkDelayMs: [950, 2100],
  },
  {
    id: "elo-2200",
    name: "Aria",
    avatar: "AR",
    elo: 2200,
    title: "Engine Lite",
    description: "A strong Stockfish-powered bot with short think time but serious tactical strength.",
    personality: "engine",
    openingStyle: "universal",
    useStockfish: true,
    stockfishDepth: 9,
    stockfishMoveTime: 1500,
    stockfishSkillLevel: 18,
    fallbackDepth: 6,
    blunderChance: 0,
    mistakeChance: 0.006,
    tacticalBias: 0.92,
    thinkDelayMs: [1100, 2300],
  },
  {
    id: "elo-2400",
    name: "Magnus",
    avatar: "MG",
    elo: 2400,
    title: "Expert Bot",
    description: "Very strong tactical and positional play with near-engine consistency.",
    personality: "universal",
    openingStyle: "classical",
    useStockfish: true,
    stockfishDepth: 11,
    stockfishMoveTime: 2200,
    stockfishSkillLevel: 20,
    fallbackDepth: 6,
    blunderChance: 0,
    mistakeChance: 0.002,
    tacticalBias: 0.96,
    thinkDelayMs: [1300, 2600],
  },
  {
    id: "stockfish",
    name: "Stockfish Max",
    avatar: "SF",
    elo: 3000,
    title: "Maximum Engine",
    description: "The strongest in-browser engine mode in this project.",
    personality: "engine",
    openingStyle: "universal",
    useStockfish: true,
    stockfishDepth: 14,
    stockfishMoveTime: 4200,
    stockfishSkillLevel: 20,
    fallbackDepth: 7,
    blunderChance: 0,
    mistakeChance: 0,
    tacticalBias: 1,
    thinkDelayMs: [1800, 3200],
  },
];

export function getBotProfile(id: BotDifficulty) {
  return botProfiles.find((profile) => profile.id === id) ?? botProfiles[5];
}
