import type { Puzzle, UserProfile } from "@/lib/types";

export const navItems = [
  { href: "/play", label: "Play" },
  { href: "/bot", label: "Bot" },
  { href: "/friend", label: "Friend" },
  { href: "/puzzles", label: "Puzzles" },
  { href: "/history", label: "History" },
  { href: "/leaderboard", label: "Leaderboard" },
  { href: "/learn", label: "Learn" },
  { href: "/pricing", label: "Pro" },
];

export const puzzles: Puzzle[] = [
  {
    id: "mate-1-back-rank",
    category: "mate in 1",
    title: "Back-rank signal",
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    bestMove: "e1e8",
    sideToMove: "white",
    explanation: "The rook reaches e8 and the king has no escape squares.",
    rating: 450,
    points: 8,
  },
  {
    id: "fork-queen-king",
    category: "fork",
    title: "Knight fork",
    fen: "2q3k1/8/2N5/8/8/8/8/4K3 w - - 0 1",
    bestMove: "c6e7",
    sideToMove: "white",
    explanation: "Ne7+ checks the king on g8 and attacks the queen on c8.",
    rating: 650,
    points: 10,
  },
  {
    id: "pin-win-piece",
    category: "pin",
    title: "Absolute pin",
    fen: "4k3/8/8/8/8/8/4r3/4R1K1 w - - 0 1",
    bestMove: "e1e2",
    sideToMove: "white",
    explanation: "Re2 pins and wins the black rook because the king sits behind it.",
    rating: 720,
    points: 11,
  },
  {
    id: "material-cleanup",
    category: "winning material",
    title: "Loose queen",
    fen: "6k1/8/8/8/8/3q4/4Q3/6K1 w - - 0 1",
    bestMove: "e2d3",
    sideToMove: "white",
    explanation: "Qxd3 removes the loose queen. Always check whether a high-value piece is simply hanging.",
    rating: 820,
    points: 12,
  },
  {
    id: "king-pawn-endgame",
    category: "endgame",
    title: "Opposition",
    fen: "8/8/8/3k4/3P4/3K4/8/8 w - - 0 1",
    bestMove: "d3e3",
    sideToMove: "white",
    explanation: "Step aside with the king to preserve opposition and support the passer.",
    rating: 900,
    points: 14,
  },
  {
    id: "mate-2-net",
    category: "mate in 2",
    title: "Build the net",
    fen: "6k1/6pp/8/8/8/8/5PPP/4RQK1 w - - 0 1",
    bestMove: "f1c4",
    line: ["f1c4", "g8h8", "e1e8"],
    sideToMove: "white",
    explanation: "Qc4+ starts a forced net with the rook controlling the back rank.",
    rating: 1050,
    points: 16,
  },
  {
    id: "black-back-rank",
    category: "mate in 1",
    title: "Black back-rank finish",
    fen: "4r1k1/5ppp/8/8/8/8/5PPP/6K1 b - - 0 1",
    bestMove: "e8e1",
    sideToMove: "black",
    explanation: "Re1# uses the rook to deliver mate while White's king has no flight square.",
    rating: 500,
    points: 8,
  },
  {
    id: "bishop-skewer",
    category: "winning material",
    title: "Skewer the queen",
    fen: "4k2q/8/8/8/8/2B5/8/4K3 w - - 0 1",
    bestMove: "c3h8",
    sideToMove: "white",
    explanation: "Bxh8 removes the loose queen along the long diagonal.",
    rating: 760,
    points: 11,
  },
  {
    id: "rook-pin",
    category: "pin",
    title: "Pin along the file",
    fen: "4k3/8/8/8/8/8/4q3/4R1K1 w - - 0 1",
    bestMove: "e1e2",
    sideToMove: "white",
    explanation: "Re2 pins the queen to the king and wins it.",
    rating: 880,
    points: 13,
  },
  {
    id: "queen-mate-corner",
    category: "mate in 1",
    title: "Corner queen mate",
    fen: "6k1/6pp/8/8/8/8/5PPP/5QK1 w - - 0 1",
    bestMove: "f1c4",
    sideToMove: "white",
    explanation: "Qc4# cuts every escape square while the queen gives direct check.",
    rating: 600,
    points: 9,
  },
  {
    id: "black-wins-queen",
    category: "fork",
    title: "Black knight fork",
    fen: "4k3/8/8/8/8/8/3n4/3K3Q b - - 0 1",
    bestMove: "d2f3",
    sideToMove: "black",
    explanation: "Nf3+ checks the king and attacks the queen on h1.",
    rating: 700,
    points: 10,
  },
  {
    id: "pawn-race",
    category: "endgame",
    title: "Promote with tempo",
    fen: "8/4P3/8/8/8/8/8/k3K3 w - - 0 1",
    bestMove: "e7e8q",
    sideToMove: "white",
    explanation: "Promote immediately. The new queen arrives with enough force to win.",
    rating: 520,
    points: 8,
  },
  {
    id: "rated-deflection-1450",
    category: "deflection",
    title: "Deflect the back-rank guard",
    fen: "4r1k1/5ppp/8/8/8/8/4QPPP/4R1K1 w - - 0 1",
    bestMove: "e2e8",
    sideToMove: "white",
    explanation: "Qxe8+ removes the defender and lands on the checking square.",
    rating: 1450,
    points: 20,
  },
  {
    id: "rated-clearance-1520",
    category: "clearance",
    title: "Clear the queen's road",
    fen: "6k1/5ppp/8/8/8/8/5PPP/2R1Q1K1 w - - 0 1",
    bestMove: "c1c8",
    sideToMove: "white",
    explanation: "Rc8+ clears the first rank and forces Black into a passive defense.",
    rating: 1520,
    points: 22,
  },
  {
    id: "rated-queen-lift-1600",
    category: "mate in 1",
    title: "Long queen lift",
    fen: "6k1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1",
    bestMove: "d1d8",
    sideToMove: "white",
    explanation: "Qd8# attacks across the eighth rank while the king is boxed in.",
    rating: 1600,
    points: 24,
  },
  {
    id: "rated-rook-sac-1680",
    category: "sacrifice",
    title: "Exchange for the queen",
    fen: "4k3/8/8/8/8/8/4q3/4R1K1 w - - 0 1",
    bestMove: "e1e2",
    sideToMove: "white",
    explanation: "Rxe2+ gives up nothing: the queen was overloaded and falls.",
    rating: 1680,
    points: 26,
  },
  {
    id: "rated-black-deflection-1760",
    category: "deflection",
    title: "Black removes the blocker",
    fen: "4r1k1/5ppp/8/8/8/8/4QPPP/6K1 b - - 0 1",
    bestMove: "e8e2",
    sideToMove: "black",
    explanation: "Rxe2 wins the queen with check-like pressure on the second rank.",
    rating: 1760,
    points: 28,
  },
  {
    id: "rated-knight-fork-1850",
    category: "fork",
    title: "Quiet square fork",
    fen: "2q3k1/8/8/8/8/3N4/8/4K3 w - - 0 1",
    bestMove: "d3e5",
    sideToMove: "white",
    explanation: "Ne5 attacks the queen and prepares a discovered check pattern.",
    rating: 1850,
    points: 30,
  },
  {
    id: "rated-bishop-corner-1950",
    category: "winning material",
    title: "Diagonal sniper",
    fen: "4k2q/8/8/8/8/8/1B6/4K3 w - - 0 1",
    bestMove: "b2h8",
    sideToMove: "white",
    explanation: "Bxh8 wins the queen from long range.",
    rating: 1950,
    points: 32,
  },
  {
    id: "rated-black-promotion-2050",
    category: "endgame",
    title: "Promote before the king arrives",
    fen: "k7/8/8/8/8/8/4p3/K7 b - - 0 1",
    bestMove: "e2e1q",
    sideToMove: "black",
    explanation: "Promote immediately and force a winning queen ending.",
    rating: 2050,
    points: 34,
  },
  {
    id: "rated-hard-backrank-2150",
    category: "mate in 1",
    title: "Hidden back-rank shot",
    fen: "6k1/5ppp/8/8/8/8/5PPP/2R3K1 w - - 0 1",
    bestMove: "c1c8",
    sideToMove: "white",
    explanation: "Rc8# uses the rook's full-file control while the pawns trap the king.",
    rating: 2150,
    points: 36,
  },
  {
    id: "rated-queen-corner-2250",
    category: "mate in 1",
    title: "Corner geometry",
    fen: "7k/6pp/8/8/8/8/6PP/5QK1 w - - 0 1",
    bestMove: "f1f8",
    sideToMove: "white",
    explanation: "Qf8# controls the corner and all flight squares.",
    rating: 2250,
    points: 38,
  },
];

export const lessons = [
  {
    title: "How pieces move",
    fen: "8/8/8/3N4/8/8/8/8 w - - 0 1",
    explanation: "Every piece has a movement pattern. Knights jump, bishops use diagonals, rooks use files and ranks.",
    task: "Find all safe knight jumps from d5.",
  },
  {
    title: "What check is",
    fen: "4k3/8/8/8/8/8/4R3/4K3 w - - 0 1",
    explanation: "Check means the king is attacked and must respond immediately.",
    task: "Move the rook to give a direct check.",
  },
  {
    title: "What checkmate is",
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    explanation: "Checkmate is check with no legal escape.",
    task: "Deliver the back-rank mate.",
  },
  {
    title: "Castling",
    fen: "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1",
    explanation: "Castling moves the king two squares and tucks the rook beside it when the path is safe.",
    task: "Castle to safety before launching an attack.",
  },
  {
    title: "Opening principles",
    fen: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
    explanation: "Fight for the center, develop pieces, and keep your king safe.",
    task: "Choose a developing response for Black.",
  },
  {
    title: "Basic tactics",
    fen: "4k3/8/8/3q4/8/3N4/8/4K3 w - - 0 1",
    explanation: "Tactics are forcing moves: checks, captures, threats, pins, forks, and skewers.",
    task: "Look for a knight fork idea.",
  },
  {
    title: "Endgame",
    fen: "8/8/8/3k4/3P4/3K4/8/8 w - - 0 1",
    explanation: "King activity and pawn promotion decide many endgames.",
    task: "Use your king to escort the pawn.",
  },
];

export const seededPlayers: UserProfile[] = [
  {
    id: "seed-1",
    email: "amina@example.com",
    username: "AminaTactics",
    city: "Almaty",
    avatar: "AT",
    rating: 1530,
    gamesCount: 88,
    wins: 53,
    losses: 24,
    draws: 11,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed-2",
    email: "sam@example.com",
    username: "SamEndgame",
    city: "New York",
    avatar: "SE",
    rating: 1475,
    gamesCount: 64,
    wins: 38,
    losses: 21,
    draws: 5,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed-3",
    email: "nora@example.com",
    username: "NoraKnight",
    city: "Astana",
    avatar: "NK",
    rating: 1410,
    gamesCount: 47,
    wins: 25,
    losses: 19,
    draws: 3,
    createdAt: new Date().toISOString(),
  },
];
