import type { Lesson, Puzzle, UserProfile } from "@/lib/types";

export const navItems = [
  { href: "/play", label: "Играть" },
  { href: "/bot", label: "Бот" },
  { href: "/friend", label: "Друг" },
  { href: "/puzzles", label: "Задачи" },
  { href: "/history", label: "История" },
  { href: "/leaderboard", label: "Рейтинг" },
  { href: "/learn", label: "Обучение" },
  { href: "/pricing", label: "Pro" },
];

export const puzzles: Puzzle[] = [
  {
    id: "mate-1-back-rank",
    category: "mate in 1",
    title: "Back-rank signal",
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    bestMove: "e1e8",
    sideToMove: "white",
    explanation: "The rook reaches e8 and the king has no escape squares.",
    hint: "Look for a rook move to the back rank.",
    rating: 450,
    points: 8,
  },
  {
    id: "fork-queen-king",
    category: "fork",
    title: "Knight fork",
    fen: "2q3k1/8/2N5/8/8/8/8/4K3 w - - 0 1",
    bestMove: "c6e7",
    sideToMove: "white",
    explanation: "Ne7+ checks the king on g8 and attacks the queen on c8.",
    hint: "A knight can attack king and queen at the same time.",
    rating: 650,
    points: 10,
  },
  {
    id: "pin-win-piece",
    category: "pin",
    title: "Absolute pin",
    fen: "4k3/8/8/8/8/8/4r3/4R1K1 w - - 0 1",
    bestMove: "e1e2",
    sideToMove: "white",
    explanation: "Re2 pins and wins the black rook because the king sits behind it.",
    hint: "Use the rook to line up the enemy rook with its king.",
    rating: 720,
    points: 11,
  },
  {
    id: "material-cleanup",
    category: "hanging piece",
    title: "Loose queen",
    fen: "6k1/8/8/8/8/3q4/4Q3/6K1 w - - 0 1",
    bestMove: "e2d3",
    sideToMove: "white",
    explanation: "Qxd3 removes the loose queen. Always check whether a high-value piece is simply hanging.",
    hint: "A queen is undefended and can be captured right now.",
    rating: 820,
    points: 12,
  },
  {
    id: "king-pawn-endgame",
    category: "endgame",
    title: "Opposition",
    fen: "8/8/8/3k4/3P4/3K4/8/8 w - - 0 1",
    bestMove: "d3e3",
    sideToMove: "white",
    explanation: "Step aside with the king to preserve opposition and support the passer.",
    hint: "Improve the king before pushing the pawn.",
    rating: 900,
    points: 14,
  },
  {
    id: "mate-2-net",
    category: "mate in 2",
    title: "Build the net",
    fen: "6k1/6pp/8/8/8/8/5PPP/4RQK1 w - - 0 1",
    bestMove: "f1c4",
    line: ["f1c4", "g8h8", "e1e8"],
    sideToMove: "white",
    explanation: "Qc4+ starts a forced net with the rook controlling the back rank.",
    hint: "Start with a queen check that forces the king to the corner.",
    rating: 1050,
    points: 16,
  },
  {
    id: "black-back-rank",
    category: "mate in 1",
    title: "Black back-rank finish",
    fen: "4r1k1/5ppp/8/8/8/8/5PPP/6K1 b - - 0 1",
    bestMove: "e8e1",
    sideToMove: "black",
    explanation: "Re1# uses the rook to deliver mate while White's king has no flight square.",
    hint: "Black has a back-rank rook mate.",
    rating: 500,
    points: 8,
  },
  {
    id: "bishop-skewer",
    category: "skewer",
    title: "Skewer the queen",
    fen: "4k2q/8/8/8/8/2B5/8/4K3 w - - 0 1",
    bestMove: "c3h8",
    sideToMove: "white",
    explanation: "Bxh8 removes the loose queen along the long diagonal.",
    hint: "The bishop can attack along the full diagonal.",
    rating: 760,
    points: 11,
  },
  {
    id: "rook-pin",
    category: "pin",
    title: "Pin along the file",
    fen: "4k3/8/8/8/8/8/4q3/4R1K1 w - - 0 1",
    bestMove: "e1e2",
    sideToMove: "white",
    explanation: "Re2 pins the queen to the king and wins it.",
    hint: "Pin the queen to the king on the e-file.",
    rating: 880,
    points: 13,
  },
  {
    id: "queen-mate-corner",
    category: "mate in 2",
    title: "Corner queen net",
    fen: "6k1/6pp/8/8/8/8/5PPP/5QK1 w - - 0 1",
    bestMove: "f1c4",
    line: ["f1c4", "g8h8", "c4c8"],
    sideToMove: "white",
    explanation: "Qc4+ drives the king to h8, then Qc8# controls the whole back rank.",
    hint: "The queen can move to the diagonal and cover the escape squares.",
    rating: 600,
    points: 9,
  },
  {
    id: "black-wins-queen",
    category: "fork",
    title: "Black knight fork",
    fen: "4k3/8/8/8/8/8/3n4/3K3Q b - - 0 1",
    bestMove: "d2f3",
    sideToMove: "black",
    explanation: "Nf3+ checks the king and attacks the queen on h1.",
    hint: "Black's knight has a fork with check.",
    rating: 700,
    points: 10,
  },
  {
    id: "pawn-race",
    category: "promotion",
    title: "Promote with tempo",
    fen: "8/4P3/8/8/8/8/8/k3K3 w - - 0 1",
    bestMove: "e7e8q",
    sideToMove: "white",
    explanation: "Promote immediately. The new queen arrives with enough force to win.",
    hint: "The pawn is already on the seventh rank.",
    rating: 520,
    points: 8,
  },
  {
    id: "rated-deflection-1450",
    category: "deflection",
    title: "Deflect the back-rank guard",
    fen: "4r1k1/5ppp/8/8/8/8/4QPPP/4R1K1 w - - 0 1",
    bestMove: "e2e8",
    sideToMove: "white",
    explanation: "Qxe8+ removes the defender and lands on the checking square.",
    hint: "Remove the rook that guards the back rank.",
    rating: 1450,
    points: 20,
  },
  {
    id: "rated-clearance-1520",
    category: "clearance",
    title: "Clear the queen's road",
    fen: "6k1/5ppp/8/8/8/8/5PPP/2R1Q1K1 w - - 0 1",
    bestMove: "c1c8",
    sideToMove: "white",
    explanation: "Rc8+ clears the first rank and forces Black into a passive defense.",
    hint: "Move the rook with tempo to open the queen's path.",
    rating: 1520,
    points: 22,
  },
  {
    id: "rated-queen-lift-1600",
    category: "mate in 1",
    title: "Long queen lift",
    fen: "6k1/5ppp/8/8/8/8/5PPP/3Q2K1 w - - 0 1",
    bestMove: "d1d8",
    sideToMove: "white",
    explanation: "Qd8# attacks across the eighth rank while the king is boxed in.",
    hint: "A queen lift to the back rank ends the game.",
    rating: 1600,
    points: 24,
  },
  {
    id: "rated-rook-sac-1680",
    category: "sacrifice",
    title: "Exchange for the queen",
    fen: "4k3/8/8/8/8/8/4q3/4R1K1 w - - 0 1",
    bestMove: "e1e2",
    sideToMove: "white",
    explanation: "Rxe2+ gives up nothing: the queen was overloaded and falls.",
    hint: "Capture the overloaded queen.",
    rating: 1680,
    points: 26,
  },
  {
    id: "rated-black-deflection-1760",
    category: "deflection",
    title: "Black removes the blocker",
    fen: "4r1k1/5ppp/8/8/8/8/4QPPP/6K1 b - - 0 1",
    bestMove: "e8e2",
    sideToMove: "black",
    explanation: "Rxe2 wins the queen with check-like pressure on the second rank.",
    hint: "Black can deflect White's queen from the second rank.",
    rating: 1760,
    points: 28,
  },
  {
    id: "rated-knight-fork-1850",
    category: "fork",
    title: "Quiet square fork",
    fen: "2q3k1/8/8/8/8/3N4/8/4K3 w - - 0 1",
    bestMove: "d3e5",
    sideToMove: "white",
    explanation: "Ne5 attacks the queen and prepares a discovered check pattern.",
    hint: "Use the knight to create threats on two targets.",
    rating: 1850,
    points: 30,
  },
  {
    id: "rated-bishop-corner-1950",
    category: "skewer",
    title: "Diagonal sniper",
    fen: "4k2q/8/8/8/8/8/1B6/4K3 w - - 0 1",
    bestMove: "b2h8",
    sideToMove: "white",
    explanation: "Bxh8 wins the queen from long range.",
    hint: "The bishop sees the queen across the board.",
    rating: 1950,
    points: 32,
  },
  {
    id: "rated-black-promotion-2050",
    category: "promotion",
    title: "Promote before the king arrives",
    fen: "k7/8/8/8/8/8/4p3/K7 b - - 0 1",
    bestMove: "e2e1q",
    sideToMove: "black",
    explanation: "Promote immediately and force a winning queen ending.",
    hint: "Black promotes before White's king can stop the pawn.",
    rating: 2050,
    points: 34,
  },
  {
    id: "rated-hard-backrank-2150",
    category: "mate in 1",
    title: "Hidden back-rank shot",
    fen: "6k1/5ppp/8/8/8/8/5PPP/2R3K1 w - - 0 1",
    bestMove: "c1c8",
    sideToMove: "white",
    explanation: "Rc8# uses the rook's full-file control while the pawns trap the king.",
    hint: "The c-file rook can reach the back rank.",
    rating: 2150,
    points: 36,
  },
  {
    id: "rated-queen-corner-2250",
    category: "mate in 1",
    title: "Corner geometry",
    fen: "7k/6pp/8/8/8/8/6PP/5QK1 w - - 0 1",
    bestMove: "f1f8",
    sideToMove: "white",
    explanation: "Qf8# controls the corner and all flight squares.",
    hint: "The queen can mate from f8.",
    rating: 2250,
    points: 38,
  },
  {
    id: "discovered-rook-attack",
    category: "discovered attack",
    title: "Open the rook",
    fen: "4k3/8/8/8/4B3/8/4r3/4R1K1 w - - 0 1",
    bestMove: "e4d3",
    sideToMove: "white",
    explanation: "Bd3 moves the bishop away and opens the rook on e1 against the rook on e2.",
    hint: "Move the front piece so the rook behind it starts attacking.",
    rating: 980,
    points: 15,
  },
  {
    id: "double-attack-queen-rook",
    category: "double attack",
    title: "Two loose pieces",
    fen: "6k1/8/8/8/3N4/8/3q4/6KR w - - 0 1",
    bestMove: "d4f3",
    sideToMove: "white",
    explanation: "Nf3 attacks the queen on d2 and the rook on h2-style route is not needed: the queen is the key loose target.",
    hint: "A knight move attacks the queen with tempo.",
    rating: 1020,
    points: 16,
  },
  {
    id: "defense-stop-mate",
    category: "defense",
    title: "Stop the back rank threat",
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 b - - 0 1",
    bestMove: "g7g6",
    sideToMove: "black",
    explanation: "g6 gives the king an escape square and removes the immediate back-rank mate idea.",
    hint: "Create luft for the king before it is too late.",
    rating: 860,
    points: 13,
  },
  {
    id: "legal-trap-full-line",
    category: "sacrifice",
    title: "Legal's mate",
    fen: "rnbqkbnr/ppp2ppp/3p4/4p3/2B1P1b1/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 4 5",
    bestMove: "f3e5",
    line: ["f3e5", "g4d1", "c4f7", "e8e7", "c3d5"],
    sideToMove: "white",
    explanation: "White ignores the queen, drags the king to e7, and finishes with Nd5#.",
    hint: "The queen can be sacrificed because the minor pieces have a forcing mate.",
    rating: 1580,
    points: 28,
  },
  {
    id: "damiano-punishment-line",
    category: "winning material",
    title: "Punish ...f6",
    fen: "rnbqkbnr/pppp2pp/5p2/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 3",
    bestMove: "f3e5",
    line: ["f3e5", "f6e5", "d1h5", "g7g6", "h5e5", "d8e7", "e5h8"],
    sideToMove: "white",
    explanation: "The knight sacrifice opens the queen checks. After Qxe5+ and Qxh8, Black's rook falls.",
    hint: "Start by taking on e5, then use the queen check on h5.",
    rating: 1660,
    points: 30,
  },
  {
    id: "greek-gift-launch",
    category: "sacrifice",
    title: "Greek gift launch",
    fen: "rnbq1rk1/ppp2ppp/3p1n2/4p3/8/2NB1N2/PPP2PPP/R2Q1RK1 w - - 0 1",
    bestMove: "d3h7",
    line: ["d3h7", "g8h7", "f3g5", "h7g8", "d1h5"],
    sideToMove: "white",
    explanation: "Bxh7+ pulls the king out, Ng5+ keeps the attack alive, and Qh5 brings the decisive threat.",
    hint: "Look for the classic bishop sacrifice on h7.",
    rating: 1780,
    points: 32,
  },
  {
    id: "queen-trap-only-move",
    category: "winning material",
    title: "Only move wins the queen",
    fen: "2r3k1/5ppp/8/8/8/2N5/4qPPP/4R1K1 w - - 0 1",
    bestMove: "e1e2",
    sideToMove: "white",
    explanation: "Re2 attacks the queen with the rook while the knight covers the key escape squares.",
    hint: "Do not trade rooks first. Trap the queen with tempo.",
    rating: 1870,
    points: 34,
  },
  {
    id: "defensive-only-luft",
    category: "defense",
    title: "One calm defensive move",
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 b - - 0 1",
    bestMove: "g7g6",
    sideToMove: "black",
    explanation: "Black must create luft. Any slow move allows Re8# on the back rank.",
    hint: "Find the quiet move that gives the king an escape square.",
    rating: 1420,
    points: 24,
  },
  {
    id: "new-back-rank-rook-1500",
    category: "mate in 1",
    title: "Rook to the back rank",
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    bestMove: "e1e8",
    sideToMove: "white",
    explanation: "Re8# attacks the king along the eighth rank while the pawns block every escape.",
    hint: "Use the rook on the open file.",
    rating: 1500,
    points: 24,
  },
  {
    id: "new-black-back-rank-rook-1510",
    category: "mate in 1",
    title: "Black rook finish",
    fen: "k3r3/8/8/8/8/8/5PPP/6K1 b - - 0 1",
    bestMove: "e8e1",
    sideToMove: "black",
    explanation: "Re1# cuts the first rank while White's own pawns trap the king.",
    hint: "Bring the rook to the first rank.",
    rating: 1510,
    points: 24,
  },
  {
    id: "new-knight-family-fork-1560",
    category: "fork",
    title: "Family fork",
    fen: "1q6/4k3/8/8/1N6/8/8/4K3 w - - 0 1",
    bestMove: "b4c6",
    sideToMove: "white",
    explanation: "Nc6+ checks the king on e7 and attacks the queen on b8.",
    hint: "A knight check can also attack the queen.",
    rating: 1560,
    points: 26,
  },
  {
    id: "new-queen-pin-1620",
    category: "pin",
    title: "Pin the queen",
    fen: "4k3/8/8/8/8/8/4q3/4R1K1 w - - 0 1",
    bestMove: "e1e2",
    sideToMove: "white",
    explanation: "Rxe2 wins the queen because the rook attacks along the pinned file.",
    hint: "Put the rook on the queen's square.",
    rating: 1620,
    points: 26,
  },
  {
    id: "new-bishop-long-skewer-1640",
    category: "skewer",
    title: "Long diagonal prize",
    fen: "4k2q/8/8/8/8/8/1B6/4K3 w - - 0 1",
    bestMove: "b2h8",
    sideToMove: "white",
    explanation: "Bxh8 wins the queen on the long diagonal.",
    hint: "Trace the bishop's diagonal to the corner.",
    rating: 1640,
    points: 26,
  },
  {
    id: "new-promotion-check-1700",
    category: "promotion",
    title: "Promote with check",
    fen: "k7/4P3/8/8/8/8/8/4K3 w - - 0 1",
    bestMove: "e7e8q",
    sideToMove: "white",
    explanation: "e8=Q+ promotes immediately and wins with a decisive queen.",
    hint: "The pawn is already one step from queening.",
    rating: 1700,
    points: 28,
  },
  {
    id: "new-black-promotion-check-1710",
    category: "promotion",
    title: "Black queens first",
    fen: "4k3/8/8/8/8/8/4p3/K7 b - - 0 1",
    bestMove: "e2e1q",
    sideToMove: "black",
    explanation: "e1=Q+ creates a new queen before White's king can help.",
    hint: "Promote with check.",
    rating: 1710,
    points: 28,
  },
  {
    id: "new-hanging-queen-1320",
    category: "hanging piece",
    title: "Free queen",
    fen: "6k1/8/8/8/8/3q4/4Q3/6K1 w - - 0 1",
    bestMove: "e2d3",
    sideToMove: "white",
    explanation: "Qxd3 simply removes the undefended queen.",
    hint: "Look for the highest-value loose piece.",
    rating: 1320,
    points: 22,
  },
  {
    id: "new-deflection-rook-1740",
    category: "deflection",
    title: "Remove the defender",
    fen: "4r1k1/5ppp/8/8/8/8/4QPPP/4R1K1 w - - 0 1",
    bestMove: "e2e8",
    sideToMove: "white",
    explanation: "Qxe8+ removes the rook and wins the back-rank defender.",
    hint: "Capture the piece that guards the back rank.",
    rating: 1740,
    points: 29,
  },
  {
    id: "new-quiet-luft-1360",
    category: "defense",
    title: "Make luft",
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 b - - 0 1",
    bestMove: "g7g6",
    sideToMove: "black",
    explanation: "g6 gives the king an escape square and stops Re8#.",
    hint: "The king needs an escape square.",
    rating: 1360,
    points: 22,
  },
  {
    id: "new-mate-two-rook-1820",
    category: "mate in 2",
    title: "Force the corner",
    fen: "6k1/6pp/8/8/8/8/6PP/4RQK1 w - - 0 1",
    bestMove: "f1c4",
    line: ["f1c4", "g8h8", "e1e8"],
    sideToMove: "white",
    explanation: "Qc4+ forces Kh8, then Re8# finishes the back rank.",
    hint: "Start with a queen check that drives the king to h8.",
    rating: 1820,
    points: 32,
  },
];

export const lessons: Lesson[] = [
  {
    id: "pieces-knight",
    category: "how pieces move",
    title: "How pieces move",
    fen: "k7/8/8/3N4/8/8/8/4K3 w - - 0 1",
    sideToMove: "white",
    explanation: "Every piece has a movement pattern. Knights jump in an L-shape and do not need an open path.",
    task: "Move the knight from d5 to f6.",
    answer: "d5f6",
    hint: "A knight moves two squares one way and one square sideways.",
    success: "Good. That L-shape jump is the core knight movement.",
  },
  {
    id: "check-rook",
    category: "check",
    title: "What check is",
    fen: "4k3/8/8/8/8/8/4R3/4K3 w - - 0 1",
    sideToMove: "white",
    explanation: "Check means the king is attacked and must respond immediately.",
    task: "Move the rook to e8 to give check.",
    answer: "e2e8",
    hint: "Rooks move in straight lines along files and ranks.",
    success: "Correct. The rook attacks the king along the e-file.",
  },
  {
    id: "checkmate-back-rank",
    category: "checkmate",
    title: "What checkmate is",
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    sideToMove: "white",
    explanation: "Checkmate is check with no legal escape.",
    task: "Deliver the back-rank mate.",
    answer: "e1e8",
    hint: "The rook can reach the back rank.",
    success: "Mate. The king is checked and has no safe square.",
  },
  {
    id: "castling-short",
    category: "castling",
    title: "Castling",
    fen: "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1",
    sideToMove: "white",
    explanation: "Castling moves the king two squares and tucks the rook beside it when the path is safe.",
    task: "Castle short with White.",
    answer: "e1g1",
    hint: "Short castling moves the king toward the h-file rook.",
    success: "Nice. Your king is safer and the rook is closer to the center.",
  },
  {
    id: "opening-develop",
    category: "opening principles",
    title: "Opening principles",
    fen: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1",
    sideToMove: "black",
    explanation: "Fight for the center, develop pieces, and keep your king safe.",
    task: "Answer 1.e4 with ...e5.",
    answer: "e7e5",
    hint: "Match White's central pawn with your own central pawn.",
    success: "Good opening answer. Black fights for the center immediately.",
  },
  {
    id: "basic-tactics-fork",
    category: "basic tactics",
    title: "Basic tactics",
    fen: "4k3/8/8/3q4/8/3N4/8/4K3 w - - 0 1",
    sideToMove: "white",
    explanation: "Tactics are forcing moves: checks, captures, threats, pins, forks, and skewers.",
    task: "Find the knight fork idea.",
    answer: "d3f4",
    hint: "Look for a knight move that checks the king and attacks the queen.",
    success: "Correct. Forks attack two valuable targets at once.",
  },
  {
    id: "forks-queen-king",
    category: "forks",
    title: "Forks",
    fen: "2q3k1/8/2N5/8/8/8/8/4K3 w - - 0 1",
    sideToMove: "white",
    explanation: "A fork attacks two or more targets with one move.",
    task: "Fork the king and queen.",
    answer: "c6e7",
    hint: "The knight can give check from e7.",
    success: "Exactly. The check wins the queen next.",
  },
  {
    id: "pins-rook",
    category: "pins",
    title: "Pins",
    fen: "4k3/8/8/8/8/8/4r3/4R1K1 w - - 0 1",
    sideToMove: "white",
    explanation: "A pinned piece cannot move without exposing something more valuable behind it.",
    task: "Pin and win the rook.",
    answer: "e1e2",
    hint: "Put your rook on the same file as the enemy rook and king.",
    success: "Good pin. The rook is stuck in front of the king.",
  },
  {
    id: "endgames-opposition",
    category: "endgames",
    title: "Endgames",
    fen: "8/8/8/3k4/3P4/3K4/8/8 w - - 0 1",
    sideToMove: "white",
    explanation: "King activity and pawn promotion decide many endgames.",
    task: "Use the king to keep opposition.",
    answer: "d3e3",
    hint: "Step aside while staying close to your pawn.",
    success: "Good endgame move. The king supports the passed pawn.",
  },
  {
    id: "king-safety-luft",
    category: "king safety",
    title: "King safety",
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 b - - 0 1",
    sideToMove: "black",
    explanation: "A trapped king is vulnerable to back-rank mates. Creating an escape square is often urgent.",
    task: "Create an escape square for Black's king.",
    answer: "g7g6",
    hint: "Move a pawn in front of the king.",
    success: "Correct. This gives the king luft and stops the mate threat.",
  },
  {
    id: "common-mistakes-hanging-queen",
    category: "common mistakes",
    title: "Common mistakes",
    fen: "6k1/8/8/8/8/3q4/4Q3/6K1 w - - 0 1",
    sideToMove: "white",
    explanation: "A common mistake is missing loose pieces. Always scan for hanging queens, rooks, and kings.",
    task: "Take the hanging queen.",
    answer: "e2d3",
    hint: "White's queen can capture on d3.",
    success: "Yes. Before making plans, collect free material.",
  },
];

export const seededPlayers: UserProfile[] = [
  {
    id: "seed-1",
    email: "amina@example.com",
    username: "AminaTactics",
    city: "Almaty",
    country: "Kazakhstan",
    avatar: "AT",
    rating: 1530,
    bulletRating: 1490,
    blitzRating: 1530,
    rapidRating: 1584,
    classicalRating: 1610,
    puzzleRating: 1715,
    gamesCount: 88,
    wins: 53,
    losses: 24,
    draws: 11,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed-2",
    email: "sam@example.com",
    username: "SamEndgame",
    city: "New York",
    country: "United States",
    avatar: "SE",
    rating: 1475,
    bulletRating: 1418,
    blitzRating: 1475,
    rapidRating: 1512,
    classicalRating: 1550,
    puzzleRating: 1660,
    gamesCount: 64,
    wins: 38,
    losses: 21,
    draws: 5,
    createdAt: new Date().toISOString(),
  },
  {
    id: "seed-3",
    email: "nora@example.com",
    username: "NoraKnight",
    city: "Astana",
    country: "Kazakhstan",
    avatar: "NK",
    rating: 1410,
    bulletRating: 1375,
    blitzRating: 1410,
    rapidRating: 1452,
    classicalRating: 1490,
    puzzleRating: 1585,
    gamesCount: 47,
    wins: 25,
    losses: 19,
    draws: 3,
    createdAt: new Date().toISOString(),
  },
];
