export type LearnLevel = "Beginner" | "Intermediate" | "Advanced";

export type LearnCourse = {
  id: string;
  title: string;
  description: string;
  level: LearnLevel;
  section: string;
};

export type LearnLesson = {
  id: string;
  courseId: string;
  title: string;
  intro: string;
  level: LearnLevel;
  theory: string[];
  rules: string[];
  fen: string;
  sideToMove: "white" | "black";
  task: string;
  answer: string;
  hint: string;
  success: string;
  summary: string[];
  quizQuestion: string;
  quizOptions: string[];
  quizAnswer: number;
  exampleFen?: string;
  exampleMoves?: string[];
};

export const learnCourses: LearnCourse[] = [
  {
    id: "chess-basics",
    title: "Chess Basics",
    description: "Board, coordinates, piece movement, check, and the first essential rules.",
    level: "Beginner",
    section: "Start from zero",
  },
  {
    id: "opening-basics",
    title: "Opening Basics",
    description: "Simple opening rules: center, development, castling, and common early mistakes.",
    level: "Beginner",
    section: "Openings",
  },
  {
    id: "tactics",
    title: "Tactics",
    description: "Learn forks, pins, skewers, double attacks, and back-rank patterns.",
    level: "Intermediate",
    section: "Tactics",
  },
  {
    id: "endgames",
    title: "Endgames",
    description: "Basic mates, opposition, pawn endings, and converting winning positions.",
    level: "Intermediate",
    section: "Endgames",
  },
  {
    id: "common-mistakes",
    title: "Common Mistakes",
    description: "Stop hanging pieces, ignoring threats, and delaying king safety.",
    level: "Beginner",
    section: "Common mistakes",
  },
];

export const learnLessons: LearnLesson[] = [
  {
    id: "basics-board-coordinates",
    courseId: "chess-basics",
    title: "Board and Coordinates",
    intro: "Every lesson starts with board orientation and square names.",
    level: "Beginner",
    theory: [
      "Files go from a to h.",
      "Ranks go from 1 to 8.",
      "Square names combine file and rank, like e4.",
    ],
    rules: [
      "White sees rank 1 closest to them.",
      "Dark square is always in each player's left corner.",
    ],
    fen: "7k/8/8/8/3Q4/8/8/4K3 w - - 0 1",
    sideToMove: "white",
    task: "Move the queen from d4 to h4 to practice board coordinates.",
    answer: "d4h4",
    hint: "Stay on rank 4 and move right to the h-file.",
    success: "Coordinates help you read moves fast and understand lessons.",
    summary: ["Files are letters.", "Ranks are numbers.", "Every square has one exact name."],
    quizQuestion: "What is the square name for file e and rank 4?",
    quizOptions: ["4e", "e4", "d5"],
    quizAnswer: 1,
    exampleMoves: ["d4d7", "d7g7", "g7g2"],
  },
  {
    id: "basics-king-move",
    courseId: "chess-basics",
    title: "How the King Moves",
    intro: "The king moves one square in any direction.",
    level: "Beginner",
    theory: [
      "The king may move one square horizontally, vertically, or diagonally.",
      "The king cannot move into check.",
    ],
    rules: ["A king is the most important piece.", "Protect your king every move."],
    fen: "7k/8/8/8/4K3/8/8/8 w - - 0 1",
    sideToMove: "white",
    task: "Move the king from e4 to e5.",
    answer: "e4e5",
    hint: "The king only steps one square.",
    success: "Kings move slowly, but they become powerful in endgames.",
    summary: ["One square only.", "All directions.", "Never move into check."],
    quizQuestion: "Can the king move two squares like a rook?",
    quizOptions: ["Yes", "No", "Only when checking"],
    quizAnswer: 1,
    exampleMoves: ["e4f5", "f5e5", "e5d4"],
  },
  {
    id: "basics-rook-move",
    courseId: "chess-basics",
    title: "How the Rook Moves",
    intro: "The rook moves in straight lines across files and ranks.",
    level: "Beginner",
    theory: [
      "Rooks move any number of squares horizontally or vertically.",
      "Rooks cannot jump over pieces.",
    ],
    rules: ["Open files make rooks stronger.", "Connected rooks often work together."],
    fen: "7k/8/8/8/4R3/8/8/4K3 w - - 0 1",
    sideToMove: "white",
    task: "Move the rook from e4 to e8.",
    answer: "e4e8",
    hint: "Stay on the same file and go straight up.",
    success: "Rooks love open lines and become strongest in the endgame.",
    summary: ["Straight lines only.", "No jumping.", "Use open files and ranks."],
    quizQuestion: "How does a rook move?",
    quizOptions: ["Only diagonally", "Straight lines", "L-shape"],
    quizAnswer: 1,
    exampleMoves: ["e4e7", "e7b7", "b7b2"],
  },
  {
    id: "basics-check-checkmate",
    courseId: "chess-basics",
    title: "Check and Checkmate",
    intro: "Check means the king is attacked. Checkmate means there is no legal escape.",
    level: "Beginner",
    theory: [
      "When your king is in check, you must answer it immediately.",
      "Checkmate ends the game.",
    ],
    rules: ["You can escape check by moving, blocking, or capturing.", "If none work, it is mate."],
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    sideToMove: "white",
    task: "Deliver checkmate in one move.",
    answer: "e1e8",
    hint: "The rook can reach the back rank.",
    success: "Mate happens when the king is attacked and has no legal defense.",
    summary: ["Check is a warning.", "Mate ends the game.", "Always look for king safety."],
    quizQuestion: "What must you do if your king is in check?",
    quizOptions: ["Ignore it", "Answer it immediately", "Offer a draw"],
    quizAnswer: 1,
    exampleMoves: ["e1e7", "e7e8"],
  },
  {
    id: "basics-castling-promotion",
    courseId: "chess-basics",
    title: "Castling and Promotion",
    intro: "Two special rules appear often in real games.",
    level: "Beginner",
    theory: [
      "Castling moves the king two squares toward the rook and brings the rook over.",
      "Promotion happens when a pawn reaches the last rank.",
    ],
    rules: ["Castle early for king safety.", "Queens are the most common promotion choice."],
    fen: "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1",
    sideToMove: "white",
    task: "Castle kingside for White.",
    answer: "e1g1",
    hint: "Move the king two squares toward the rook on h1.",
    success: "Castling protects the king and activates the rook at the same time.",
    summary: ["Castle for safety.", "Promote on the last rank.", "Special rules matter."],
    quizQuestion: "Why is castling useful?",
    quizOptions: ["It protects the king", "It sacrifices the queen", "It ends the game"],
    quizAnswer: 0,
    exampleFen: "7k/4P3/8/8/8/8/8/4K3 w - - 0 1",
    exampleMoves: ["e7e8q"],
  },
  {
    id: "opening-center",
    courseId: "opening-basics",
    title: "Control the Center",
    intro: "Good openings fight for e4, d4, e5, and d5.",
    level: "Beginner",
    theory: [
      "Central squares give your pieces more space.",
      "Pawns and pieces should support the center together.",
    ],
    rules: ["Play useful moves with purpose.", "Central control helps both attack and defense."],
    fen: "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1",
    sideToMove: "white",
    task: "Play a strong central first move for White.",
    answer: "e2e4",
    hint: "Put a pawn in the center.",
    success: "Central pawns help your pieces develop naturally.",
    summary: ["Fight for the center.", "Use pawns and pieces together.", "Space matters early."],
    quizQuestion: "Which squares are the main center squares?",
    quizOptions: ["a1, h8, a8, h1", "e4, d4, e5, d5", "b2, g2, b7, g7"],
    quizAnswer: 1,
    exampleMoves: ["e2e4", "e7e5", "d2d4"],
  },
  {
    id: "opening-develop-pieces",
    courseId: "opening-basics",
    title: "Develop Your Pieces",
    intro: "Bring knights and bishops out quickly instead of moving the same piece again and again.",
    level: "Beginner",
    theory: [
      "Development means moving pieces from the back rank into active squares.",
      "Knights usually develop before bishops in simple positions.",
    ],
    rules: ["Do not waste tempi.", "Try to improve a new piece each move."],
    fen: "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3",
    sideToMove: "white",
    task: "Develop another piece for White.",
    answer: "f1c4",
    hint: "Bring the bishop toward the center and f7.",
    success: "Piece development helps you coordinate for the middlegame.",
    summary: ["Develop quickly.", "Use active squares.", "Do not repeat one piece too early."],
    quizQuestion: "What is development in the opening?",
    quizOptions: ["Trading queens early", "Activating your pieces", "Pushing random pawns"],
    quizAnswer: 1,
    exampleMoves: ["f1c4", "g8f6", "d2d3"],
  },
  {
    id: "opening-castle-early",
    courseId: "opening-basics",
    title: "Castle Early",
    intro: "One of the safest habits for beginners is castling before attacking.",
    level: "Beginner",
    theory: [
      "Castling hides the king behind pawns.",
      "It also connects the rooks more quickly.",
    ],
    rules: ["Do not start a wing attack with your king still in the center.", "Castle once the path is clear."],
    fen: "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
    sideToMove: "white",
    task: "Choose the safe king move for White.",
    answer: "e1g1",
    hint: "Castle before starting a direct attack.",
    success: "King safety comes before ambitious attacks.",
    summary: ["Castle when you can.", "Safety first.", "Connected rooks are a bonus."],
    quizQuestion: "Why should many beginners castle early?",
    quizOptions: ["To protect the king", "To move the queen faster", "To avoid development"],
    quizAnswer: 0,
    exampleMoves: ["e1g1", "f8c5", "c2c3"],
  },
  {
    id: "opening-queen-early",
    courseId: "opening-basics",
    title: "Do Not Bring the Queen Out Early",
    intro: "The queen is strong, but early queen moves often lose time.",
    level: "Beginner",
    theory: [
      "The queen is a target for smaller pieces.",
      "Developing minor pieces first is usually better.",
    ],
    rules: ["Do not chase quick attacks with the queen alone.", "Build your position first."],
    fen: "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPPQPPP/RNB1KB1R w KQkq - 2 3",
    sideToMove: "white",
    task: "Instead of another queen move, develop a piece.",
    answer: "b1c3",
    hint: "Bring a knight toward the center.",
    success: "Minor-piece development is usually more useful than an early queen adventure.",
    summary: ["The queen is valuable.", "Do not waste time.", "Develop pieces first."],
    quizQuestion: "Why can early queen moves be a mistake?",
    quizOptions: ["The queen becomes a target", "Queens cannot move early", "It is illegal"],
    quizAnswer: 0,
    exampleMoves: ["b1c3", "g8f6", "f1c4"],
  },
  {
    id: "opening-basic-trap",
    courseId: "opening-basics",
    title: "Basic Opening Trap",
    intro: "Opening traps are short tactical ideas that punish careless moves.",
    level: "Beginner",
    theory: [
      "A trap works because one side ignores development or king safety.",
      "The best defense is still good opening principles.",
    ],
    rules: ["Do not grab material blindly.", "Check if your opponent has a tactical reply."],
    fen: "rnbqkbnr/ppp2ppp/3p4/4p3/2B1P1b1/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 4 5",
    sideToMove: "white",
    task: "Play the tactical shot that starts Legal's Mate idea.",
    answer: "f3e5",
    hint: "White can ignore the queen and use the knight.",
    success: "Good traps still rely on forcing moves like checks and threats.",
    summary: ["Watch for tactical punishments.", "Development matters.", "Checks and threats come first."],
    quizQuestion: "What usually causes opening traps?",
    quizOptions: ["Random luck", "Ignoring principles and tactics", "Moving too slowly in endgames"],
    quizAnswer: 1,
    exampleMoves: ["f3e5", "g4d1", "c4f7"],
  },
  {
    id: "tactics-fork",
    courseId: "tactics",
    title: "Fork",
    intro: "A fork attacks two targets at the same time.",
    level: "Intermediate",
    theory: [
      "Knights are especially strong fork pieces.",
      "Checks make forks even stronger because the king must respond.",
    ],
    rules: ["Look for loose queens near the king.", "Always scan for double attacks."],
    fen: "1q6/4k3/8/8/1N6/8/8/4K3 w - - 0 1",
    sideToMove: "white",
    task: "Find the knight fork.",
    answer: "b4c6",
    hint: "A checking knight move attacks the queen too.",
    success: "Forks win material because one move creates two threats.",
    summary: ["One piece attacks two targets.", "Checks increase tactical power.", "Knights love forks."],
    quizQuestion: "Which piece is especially famous for forks?",
    quizOptions: ["Knight", "Pawn", "King"],
    quizAnswer: 0,
    exampleMoves: ["b4c6"],
  },
  {
    id: "tactics-pin",
    courseId: "tactics",
    title: "Pin",
    intro: "A pin freezes a piece because moving it would expose something more valuable.",
    level: "Intermediate",
    theory: [
      "Absolute pins are against the king.",
      "Relative pins still matter if a queen or rook is behind the piece.",
    ],
    rules: ["Pinned pieces often defend less.", "Try to attack pinned pieces again."],
    fen: "4k3/8/8/8/8/8/4q3/4R1K1 w - - 0 1",
    sideToMove: "white",
    task: "Play the move that pins and wins the queen.",
    answer: "e1e2",
    hint: "Use the rook on the e-file.",
    success: "Pins create tactical pressure because the pinned piece cannot move freely.",
    summary: ["A pin restricts movement.", "Kings create absolute pins.", "Attack pinned pieces."],
    quizQuestion: "What is an absolute pin?",
    quizOptions: ["Pinned to the king", "Pinned to a pawn", "Pinned on a dark square"],
    quizAnswer: 0,
    exampleMoves: ["e1e2"],
  },
  {
    id: "tactics-skewer",
    courseId: "tactics",
    title: "Skewer",
    intro: "A skewer attacks a valuable piece first, forcing it to move and exposing the piece behind it.",
    level: "Intermediate",
    theory: [
      "Skewers often happen on files, ranks, and diagonals.",
      "Bishops and rooks create many skewers.",
    ],
    rules: ["Line pieces need open lines.", "Look behind the first target."],
    fen: "4k2q/8/8/8/8/2B5/8/4K3 w - - 0 1",
    sideToMove: "white",
    task: "Use the bishop to win the queen.",
    answer: "c3h8",
    hint: "The long diagonal is open.",
    success: "A skewer works by forcing the front piece away from the back piece.",
    summary: ["Attack the valuable piece first.", "Win what stands behind it.", "Use open lines."],
    quizQuestion: "What usually stands in front during a skewer?",
    quizOptions: ["The more valuable piece", "The pawn", "Nothing"],
    quizAnswer: 0,
    exampleMoves: ["c3h8"],
  },
  {
    id: "tactics-double-attack",
    courseId: "tactics",
    title: "Double Attack",
    intro: "A double attack is any move that creates two threats at once.",
    level: "Intermediate",
    theory: [
      "Forks are one kind of double attack.",
      "Queens and knights often create flexible double attacks.",
    ],
    rules: ["Scan for checks plus material threats.", "Loose pieces are double-attack targets."],
    fen: "6k1/8/8/8/3N4/8/3q4/6KR w - - 0 1",
    sideToMove: "white",
    task: "Play the knight move that creates multiple threats.",
    answer: "d4f3",
    hint: "The knight jumps closer to the queen.",
    success: "Double attacks overload your opponent because one move is not enough to solve both problems.",
    summary: ["Two threats in one move.", "Checks are powerful.", "Loose pieces make tactics easier."],
    quizQuestion: "What makes a double attack strong?",
    quizOptions: ["It creates only one idea", "The opponent must answer two threats", "It only works in endgames"],
    quizAnswer: 1,
    exampleMoves: ["d4f3"],
  },
  {
    id: "tactics-back-rank",
    courseId: "tactics",
    title: "Back Rank Mate",
    intro: "Back-rank tactics happen when the king has no escape square behind its pawns.",
    level: "Intermediate",
    theory: [
      "A trapped king on the last rank is vulnerable to rooks and queens.",
      "Creating luft with a pawn move often stops this theme.",
    ],
    rules: ["Watch your king's escape squares.", "Open files increase back-rank danger."],
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1",
    sideToMove: "white",
    task: "Deliver the back-rank mate.",
    answer: "e1e8",
    hint: "The rook can climb the file.",
    success: "Back-rank motifs are among the most common tactical patterns in chess.",
    summary: ["A boxed king is vulnerable.", "Rooks love open files.", "Create luft in defense."],
    quizQuestion: "What often prevents back-rank mate?",
    quizOptions: ["A luft move", "Trading queens", "Moving the same rook twice"],
    quizAnswer: 0,
    exampleMoves: ["e1e8"],
  },
  {
    id: "endgames-queen-mate",
    courseId: "endgames",
    title: "Queen Mate",
    intro: "Queen and king versus king is a basic winning ending.",
    level: "Intermediate",
    theory: [
      "The queen cuts off files, ranks, and diagonals.",
      "Bring your king closer to help deliver mate.",
    ],
    rules: ["Do not give pointless checks forever.", "Reduce the king's box step by step."],
    fen: "7k/5Q2/6K1/8/8/8/8/8 w - - 0 1",
    sideToMove: "white",
    task: "Finish the mate in one.",
    answer: "f7g7",
    hint: "The queen mates by covering the escape squares.",
    success: "Basic mating nets are essential endgame knowledge.",
    summary: ["Use the queen to shrink the box.", "Bring the king close.", "Finish carefully."],
    quizQuestion: "What helps the queen mate faster?",
    quizOptions: ["A nearby king", "A far-away rook", "Random pawn checks"],
    quizAnswer: 0,
    exampleMoves: ["f7g7"],
  },
  {
    id: "endgames-rook-mate",
    courseId: "endgames",
    title: "Rook Mate",
    intro: "Rook and king versus king is another must-know basic ending.",
    level: "Intermediate",
    theory: [
      "The rook cuts the king off rank by rank.",
      "Your king supports the rook and removes escape squares.",
    ],
    rules: ["Do not let your rook hang.", "Use the rook from a safe distance."],
    fen: "k7/8/1K6/1R6/8/8/8/8 w - - 0 1",
    sideToMove: "white",
    task: "Deliver the mate with the rook.",
    answer: "b5b8",
    hint: "The rook can check along the eighth rank.",
    success: "Rook mates teach coordination between king and rook.",
    summary: ["Cut off the king.", "Use your king too.", "Rook mates are technical."],
    quizQuestion: "What is the rook's main job in rook mate?",
    quizOptions: ["Cut off squares", "Jump over pieces", "Guard its own king only"],
    quizAnswer: 0,
    exampleMoves: ["b5b8"],
  },
  {
    id: "endgames-king-pawn",
    courseId: "endgames",
    title: "King and Pawn",
    intro: "Many games simplify into a king-and-pawn race.",
    level: "Intermediate",
    theory: [
      "The king must support the pawn.",
      "Opposition often decides whether the pawn promotes.",
    ],
    rules: ["Do not rush the pawn.", "Improve the king first when needed."],
    fen: "8/8/8/3k4/3P4/3K4/8/8 w - - 0 1",
    sideToMove: "white",
    task: "Play the key king move to keep the opposition idea.",
    answer: "d3e3",
    hint: "Improve the king before pushing.",
    success: "King activity wins pawn endings more often than beginners expect.",
    summary: ["King first.", "Support the pawn.", "Opposition matters."],
    quizQuestion: "What is usually strongest in pawn endings?",
    quizOptions: ["King activity", "Early queen attack", "Random checks"],
    quizAnswer: 0,
    exampleMoves: ["d3e3", "d5c4", "e3e4"],
  },
  {
    id: "endgames-opposition",
    courseId: "endgames",
    title: "Opposition",
    intro: "Opposition means forcing the enemy king to move away first.",
    level: "Intermediate",
    theory: [
      "Kings facing each other with one square between them often create opposition.",
      "The side to move can be worse in pure king endings.",
    ],
    rules: ["Count king squares carefully.", "Opposition is about tempo and entry."],
    fen: "8/8/8/4k3/8/4K3/8/8 w - - 0 1",
    sideToMove: "white",
    task: "Take the opposition with White.",
    answer: "e3e4",
    hint: "Step directly in front of the king.",
    success: "Opposition helps your king break through in many endings.",
    summary: ["Face the king.", "Tempo matters.", "Use opposition to enter."],
    quizQuestion: "What does opposition help you do?",
    quizOptions: ["Win space with the king", "Develop the queen", "Castle late"],
    quizAnswer: 0,
    exampleMoves: ["e3e4", "e5e6", "e4d4"],
  },
  {
    id: "endgames-passed-pawn",
    courseId: "endgames",
    title: "Passed Pawn",
    intro: "A passed pawn has no enemy pawns stopping it on its file or neighbor files.",
    level: "Intermediate",
    theory: [
      "Passed pawns must often be pushed.",
      "Promotion threats create winning chances even before the pawn reaches the end.",
    ],
    rules: ["Push passed pawns with support.", "Calculate promotion races carefully."],
    fen: "8/4P3/8/8/8/8/8/k3K3 w - - 0 1",
    sideToMove: "white",
    task: "Promote the passed pawn.",
    answer: "e7e8q",
    hint: "The pawn is ready for promotion.",
    success: "Passed pawns are one of the biggest endgame advantages.",
    summary: ["Passed pawns are powerful.", "Promotion wins games.", "Support the pawn."],
    quizQuestion: "Why is a passed pawn dangerous?",
    quizOptions: ["It threatens promotion", "It moves like a rook", "It can castle"],
    quizAnswer: 0,
    exampleMoves: ["e7e8q"],
  },
  {
    id: "mistakes-hanging-pieces",
    courseId: "common-mistakes",
    title: "Do Not Hang Pieces",
    intro: "Loose pieces disappear quickly in practical chess.",
    level: "Beginner",
    theory: [
      "A hanging piece is undefended and can be taken.",
      "Before every move, ask what your opponent attacks.",
    ],
    rules: ["Scan checks, captures, and threats.", "Notice undefended queens and rooks first."],
    fen: "6k1/8/8/8/8/3q4/4Q3/6K1 w - - 0 1",
    sideToMove: "white",
    task: "Win the hanging queen immediately.",
    answer: "e2d3",
    hint: "An undefended queen is ready to be captured.",
    success: "Spotting loose pieces is one of the fastest ways to improve.",
    summary: ["Loose pieces drop.", "Always scan captures.", "Blunder-check every move."],
    quizQuestion: "What is a hanging piece?",
    quizOptions: ["An undefended piece", "A promoted pawn", "A checked king"],
    quizAnswer: 0,
    exampleMoves: ["e2d3"],
  },
  {
    id: "mistakes-check-threats",
    courseId: "common-mistakes",
    title: "Check Opponent Threats",
    intro: "Do not only think about your own ideas. See what your opponent wants too.",
    level: "Beginner",
    theory: [
      "Many blunders happen because a player ignores one direct threat.",
      "Back-rank threats are especially common.",
    ],
    rules: ["Before your move, ask: what is my opponent threatening?", "Create luft when needed."],
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 b - - 0 1",
    sideToMove: "black",
    task: "Defend against the back-rank mate threat.",
    answer: "g7g6",
    hint: "Give your king an escape square.",
    success: "Defense starts with recognizing the threat in time.",
    summary: ["See the threat.", "Answer it early.", "A small defensive move can save the game."],
    quizQuestion: "What is the first step in defense?",
    quizOptions: ["Recognize the threat", "Attack faster", "Move the queen randomly"],
    quizAnswer: 0,
    exampleMoves: ["g7g6"],
  },
  {
    id: "mistakes-queen-early",
    courseId: "common-mistakes",
    title: "Do Not Move the Queen Too Early",
    intro: "An early queen often becomes a target instead of a hero.",
    level: "Beginner",
    theory: [
      "The queen is strong, but your minor pieces need development first.",
      "Opponents gain time by attacking the queen repeatedly.",
    ],
    rules: ["Use knights and bishops first.", "Do not chase cheap attacks with only the queen."],
    fen: "r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPPQPPP/RNB1KB1R w KQkq - 2 3",
    sideToMove: "white",
    task: "Play a better developing move instead of another queen move.",
    answer: "b1c3",
    hint: "Develop a knight naturally.",
    success: "Good openings rely on quick development, not queen adventures.",
    summary: ["Queen is valuable.", "Develop first.", "Do not lose tempi."],
    quizQuestion: "Why is an early queen often risky?",
    quizOptions: ["It is illegal", "It becomes a target", "It cannot capture"],
    quizAnswer: 1,
    exampleMoves: ["b1c3", "g8f6", "f1c4"],
  },
  {
    id: "mistakes-not-castling",
    courseId: "common-mistakes",
    title: "Castle Before Attacking",
    intro: "Many attacks fail because the king remains in the center.",
    level: "Beginner",
    theory: [
      "Castling is both a defensive move and a rook-development move.",
      "An exposed king makes your whole position unstable.",
    ],
    rules: ["Prepare the attack after king safety.", "Use castling to connect the rooks."],
    fen: "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
    sideToMove: "white",
    task: "Make the safe move first.",
    answer: "e1g1",
    hint: "Castle kingside.",
    success: "Good attacks start from safe positions.",
    summary: ["Safety before attack.", "Castle early.", "Connected rooks help later."],
    quizQuestion: "What often comes before a successful attack?",
    quizOptions: ["King safety", "Queen sacrifice", "Random pawn storm"],
    quizAnswer: 0,
    exampleMoves: ["e1g1"],
  },
  {
    id: "mistakes-back-rank-weakness",
    courseId: "common-mistakes",
    title: "Watch Your Back Rank",
    intro: "If your king has no escape square, one rook can end the game.",
    level: "Beginner",
    theory: [
      "Back-rank weakness is caused by trapped kings and unmoved pawns.",
      "A small luft move can solve a big problem.",
    ],
    rules: ["Give your king air when needed.", "Notice open files aimed at your king."],
    fen: "6k1/5ppp/8/8/8/8/5PPP/4R1K1 b - - 0 1",
    sideToMove: "black",
    task: "Prevent the back-rank mate with the right pawn move.",
    answer: "g7g6",
    hint: "Create one escape square.",
    success: "A single luft move often saves the whole game.",
    summary: ["Back-rank danger is common.", "Luft prevents mate.", "King escape squares matter."],
    quizQuestion: "How do you often stop back-rank mate?",
    quizOptions: ["Create luft", "Move the queen to the corner", "Trade a bishop"],
    quizAnswer: 0,
    exampleMoves: ["g7g6"],
  },
];

export function lessonsForCourse(courseId: string) {
  return learnLessons.filter((lesson) => lesson.courseId === courseId);
}
